version: "3"
services:
  db:
    image: postgres:15.1
    container_name: postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
 
  api:
    build: 
      context: ./blog-api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 3
    networks:
      - postgres

  front:
    build: 
      context: ./blog-ui
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '3000:3000'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 3
    env_file:
      - .env
 
networks:
  postgres:
    driver: bridge
    