version: "3"
services:
  db:
    image: postgres:15.1
    container_name: postgres
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - "5433:5432"
    env_file:
      - ./blog-api/.env
 
  api:
    build: 
      context: ./blog-api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./blog-api/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - postgres

  front:
    build: 
      context: ./blog-ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
 
networks:
  postgres:
    driver: bridge
    